if(NOT CMAKE_SYSROOT)
  message(FATAL_ERROR "CMAKE_SYSROOT not set.")
else()
  message(STATUS "Radxa CMAKE_SYSROOT: ${CMAKE_SYSROOT}")
endif()

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CROSS_GNU aarch64-rpi3-linux-gnu)
set(CMAKE_C_COMPILER ${CROSS_GNU}-gcc)
set(CMAKE_CXX_COMPILER ${CROSS_GNU}-g++)
set(CMAKE_Fortran_COMPILER ${CROSS_GNU}-gfortran)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_LIBRARY_ARCHITECTURE aarch64-linux-gnu)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE arm64)

set(ENV{PKG_CONFIG_LIBDIR} "${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig")
